"""tests/test_context_guard.py — scripts/hooks/context_guard.js (PreToolUse Read|Bash).

Fail-open everywhere EXCEPT the two named denial classes (exit 2 + '[context-guard BLOCK]' on
stderr). Every test drives the real committed hook + rules file as a subprocess -- never requires
the .js directly (same posture as tests/test_hard_ceiling_guard.py)."""
import json
import os
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
HOOK = REPO / "scripts" / "hooks" / "context_guard.js"
RULES = REPO / "scripts" / "hooks" / "context_guard.rules.yaml"


def run_hook(tmp_path, event, store_dir=None, extra_env=None):
    pf = tmp_path / "payload.json"
    pf.write_text(json.dumps(event), encoding="utf-8")
    env = {**os.environ}
    if store_dir is not None:
        env["KB_CONTEXT_STORE_DIR"] = str(store_dir)
    if extra_env:
        env.update(extra_env)
    return subprocess.run(["node", str(HOOK)], input=pf.read_bytes(), capture_output=True, env=env)


def write_session_model(store_dir, session_id, model):
    store_dir.mkdir(parents=True, exist_ok=True)
    (store_dir / f"{session_id}.ctx.md").write_text(
        "<!-- kb context-lifecycle store. Generated by the INERT context-lifecycle hooks; do not hand-edit. -->\n\n"
        f"## Session model\n\n{model}\n",
        encoding="utf-8",
    )


def read_event(session_id, cwd, file_path):
    return {"hook_event_name": "PreToolUse", "tool_name": "Read", "session_id": session_id,
            "cwd": str(cwd), "tool_input": {"file_path": str(file_path)}}


def bash_event(command, cwd):
    return {"hook_event_name": "PreToolUse", "tool_name": "Bash", "cwd": str(cwd),
            "tool_input": {"command": command}}


# ── Read: PDF/image + Fable/Opus ─────────────────────────────────────────────────────────────

def test_pdf_read_denied_for_opus(tmp_path):
    store_dir = tmp_path / "store"
    write_session_model(store_dir, "sess-1", "claude-opus-5")
    pdf = tmp_path / "doc.pdf"
    pdf.write_bytes(b"%PDF-1.4 fake")
    r = run_hook(tmp_path, read_event("sess-1", tmp_path, pdf), store_dir)
    assert r.returncode == 2
    assert b"[context-guard BLOCK]" in r.stderr
    assert b"haiku" in r.stderr


def test_pdf_read_denied_for_fable(tmp_path):
    store_dir = tmp_path / "store"
    write_session_model(store_dir, "sess-f", "claude-fable-5-1")
    pdf = tmp_path / "doc.pdf"
    pdf.write_bytes(b"%PDF-1.4 fake")
    r = run_hook(tmp_path, read_event("sess-f", tmp_path, pdf), store_dir)
    assert r.returncode == 2


def test_pdf_read_allowed_for_sonnet(tmp_path):
    store_dir = tmp_path / "store"
    write_session_model(store_dir, "sess-2", "claude-sonnet-5")
    pdf = tmp_path / "doc.pdf"
    pdf.write_bytes(b"%PDF-1.4 fake")
    r = run_hook(tmp_path, read_event("sess-2", tmp_path, pdf), store_dir)
    assert r.returncode == 0 and r.stderr.strip() == b""


def test_pdf_read_allowed_when_no_model_note(tmp_path):
    store_dir = tmp_path / "store"
    pdf = tmp_path / "doc.pdf"
    pdf.write_bytes(b"%PDF-1.4 fake")
    r = run_hook(tmp_path, read_event("sess-none", tmp_path, pdf), store_dir)
    assert r.returncode == 0


def test_txt_read_allowed_for_opus(tmp_path):
    store_dir = tmp_path / "store"
    write_session_model(store_dir, "sess-3", "claude-opus-5")
    txt = tmp_path / "notes.txt"
    txt.write_text("hi", encoding="utf-8")
    r = run_hook(tmp_path, read_event("sess-3", tmp_path, txt), store_dir)
    assert r.returncode == 0


# ── Bash: pytest / git log / find / — with escapes ───────────────────────────────────────────

def test_pytest_without_filter_denied(tmp_path):
    r = run_hook(tmp_path, bash_event("pytest tests/", tmp_path))
    assert r.returncode == 2
    assert b"pytest -q" in r.stderr


def test_pytest_with_q_allowed(tmp_path):
    r = run_hook(tmp_path, bash_event("pytest tests/ -q", tmp_path))
    assert r.returncode == 0


def test_pytest_piped_to_tail_allowed(tmp_path):
    r = run_hook(tmp_path, bash_event("pytest tests/ | tail -n 30", tmp_path))
    assert r.returncode == 0


def test_git_log_unbounded_denied(tmp_path):
    r = run_hook(tmp_path, bash_event("git log", tmp_path))
    assert r.returncode == 2


def test_git_log_with_n_allowed(tmp_path):
    r = run_hook(tmp_path, bash_event("git log -n 20", tmp_path))
    assert r.returncode == 0


def test_git_log_oneline_allowed(tmp_path):
    r = run_hook(tmp_path, bash_event("git log --oneline -n 20", tmp_path))
    assert r.returncode == 0


def test_find_root_denied(tmp_path):
    r = run_hook(tmp_path, bash_event("find / -name '*.log'", tmp_path))
    assert r.returncode == 2


def test_find_scoped_allowed(tmp_path):
    r = run_hook(tmp_path, bash_event("find . -name '*.log'", tmp_path))
    assert r.returncode == 0


def test_cat_large_file_denied(tmp_path):
    big = tmp_path / "big.log"
    big.write_bytes(b"x" * (60 * 1024))
    r = run_hook(tmp_path, bash_event(f"cat {big.name}", tmp_path))
    assert r.returncode == 2
    assert b"50 KB" in r.stderr


def test_cat_small_file_allowed(tmp_path):
    small = tmp_path / "small.log"
    small.write_bytes(b"x" * 100)
    r = run_hook(tmp_path, bash_event(f"cat {small.name}", tmp_path))
    assert r.returncode == 0


def test_cat_large_file_piped_to_tail_allowed(tmp_path):
    big = tmp_path / "big.log"
    big.write_bytes(b"x" * (60 * 1024))
    r = run_hook(tmp_path, bash_event(f"cat {big.name} | tail -n 50", tmp_path))
    assert r.returncode == 0


def test_cat_nonexistent_file_fails_open(tmp_path):
    r = run_hook(tmp_path, bash_event("cat does-not-exist.log", tmp_path))
    assert r.returncode == 0  # can't stat it -> not this hook's job to say so


def test_benign_bash_silent(tmp_path):
    r = run_hook(tmp_path, bash_event("echo hello", tmp_path))
    assert r.returncode == 0 and r.stderr.strip() == b""


# ── fail-open ─────────────────────────────────────────────────────────────────────────────────

def test_fail_open_on_garbage(tmp_path):
    r = subprocess.run(["node", str(HOOK)], input=b"not json", capture_output=True)
    assert r.returncode == 0 and r.stderr.strip() == b""


def test_fail_open_on_empty_stdin(tmp_path):
    r = subprocess.run(["node", str(HOOK)], input=b"", capture_output=True)
    assert r.returncode == 0 and r.stderr.strip() == b""


def test_fail_open_on_foreign_event(tmp_path):
    r = run_hook(tmp_path, {"hook_event_name": "Stop"})
    assert r.returncode == 0 and r.stderr.strip() == b""


def test_fail_open_on_unrecognised_tool(tmp_path):
    r = run_hook(tmp_path, {"hook_event_name": "PreToolUse", "tool_name": "Edit", "tool_input": {}})
    assert r.returncode == 0


# ── config shape pin ──────────────────────────────────────────────────────────────────────────

def test_rules_file_has_required_rule_ids():
    """Pin the config's shape: context_guard.js's hand-rolled parser (same pattern as
    lib/model_audit.js's parseAllowedModels) has no schema validation -- a reformat that drops a
    field fails OPEN (silently fewer rules), never crashes, so this is the safety net."""
    text = RULES.read_text(encoding="utf-8")
    assert "read_extensions:" in text and "read_models:" in text and "rules:" in text
    for required in ("bash-pytest-no-filter", "bash-git-log-unbounded", "bash-find-root", "bash-cat-large-file"):
        assert f"id: {required}" in text


# ── transcript-tail model fallback (ruling 2026-09-11: event.model is ALWAYS absent, so the
#    store's own '## Session model' note is empty in real use -- this fallback path is what
#    actually fires in production, not the store-only lookup above) ────────────────────────────

def write_transcript(path_, lines):
    path_.write_text("\n".join(lines) + "\n", encoding="utf-8")


def test_transcript_tail_fallback_denies_for_fable(tmp_path):
    store_dir = tmp_path / "store"
    transcript = tmp_path / "session.jsonl"
    write_transcript(transcript, ['{"type":"assistant","message":{"model":"claude-fable-5-1"}}'])
    pdf = tmp_path / "doc.pdf"
    pdf.write_bytes(b"%PDF-1.4 fake")
    event = read_event("sess-tail", tmp_path, pdf)
    event["transcript_path"] = str(transcript)
    r = run_hook(tmp_path, event, store_dir)
    assert r.returncode == 2
    assert b"[context-guard BLOCK]" in r.stderr


def test_transcript_tail_fallback_allows_for_sonnet(tmp_path):
    store_dir = tmp_path / "store"
    transcript = tmp_path / "session.jsonl"
    write_transcript(transcript, ['{"type":"assistant","message":{"model":"claude-sonnet-5"}}'])
    pdf = tmp_path / "doc.pdf"
    pdf.write_bytes(b"%PDF-1.4 fake")
    event = read_event("sess-tail2", tmp_path, pdf)
    event["transcript_path"] = str(transcript)
    r = run_hook(tmp_path, event, store_dir)
    assert r.returncode == 0


def test_missing_transcript_allows(tmp_path):
    store_dir = tmp_path / "store"
    pdf = tmp_path / "doc.pdf"
    pdf.write_bytes(b"%PDF-1.4 fake")
    event = read_event("sess-notrans", tmp_path, pdf)
    event["transcript_path"] = str(tmp_path / "does-not-exist.jsonl")
    r = run_hook(tmp_path, event, store_dir)
    assert r.returncode == 0


def test_transcript_tail_uses_last_occurrence_within_the_tail_not_the_head(tmp_path):
    """A huge transcript: a decoy (allowed) model near byte 0, the real (denied) model only in the
    last 64 KB. Getting this right is only possible with a TAIL read, not a head-capped read --
    a head-capped read would see the decoy and wrongly allow."""
    store_dir = tmp_path / "store"
    transcript = tmp_path / "big.jsonl"
    lines = ['{"message":{"model":"claude-sonnet-5"}}']
    lines += ["x" * 200] * 2000  # far more than 64 KB of padding
    lines.append('{"message":{"model":"claude-fable-5-1"}}')
    transcript.write_text("\n".join(lines) + "\n", encoding="utf-8")
    assert transcript.stat().st_size > 128 * 1024

    pdf = tmp_path / "doc.pdf"
    pdf.write_bytes(b"%PDF-1.4 fake")
    event = read_event("sess-huge", tmp_path, pdf)
    event["transcript_path"] = str(transcript)
    r = run_hook(tmp_path, event, store_dir)
    assert r.returncode == 2  # the tail's fable note wins, not the head's sonnet decoy


def test_transcript_tail_model_is_cached_into_store(tmp_path):
    store_dir = tmp_path / "store"
    transcript = tmp_path / "session.jsonl"
    write_transcript(transcript, ['{"message":{"model":"claude-fable-5-1"}}'])
    pdf = tmp_path / "doc.pdf"
    pdf.write_bytes(b"%PDF-1.4 fake")
    event = read_event("sess-cache", tmp_path, pdf)
    event["transcript_path"] = str(transcript)

    r1 = run_hook(tmp_path, event, store_dir)
    assert r1.returncode == 2

    # Remove the transcript entirely: if the model was NOT cached, this now falls back to
    # "no model note anywhere" and would ALLOW -- so a deny here proves the cache wrote through.
    transcript.unlink()
    r2 = run_hook(tmp_path, event, store_dir)
    assert r2.returncode == 2

    store_file = store_dir / "sess-cache.ctx.md"
    assert "claude-fable-5-1" in store_file.read_text(encoding="utf-8")


# ── malformed rules file → fail open ─────────────────────────────────────────────────────────

def test_malformed_rules_file_allows_everything(tmp_path):
    bad_rules = tmp_path / "bad-rules.yaml"
    bad_rules.write_text("this is not: [valid, at, all\nrandom prose with no structure\n", encoding="utf-8")
    r = run_hook(tmp_path, bash_event("pytest tests/", tmp_path),
                 extra_env={"KB_CONTEXT_GUARD_RULES_PATH": str(bad_rules)})
    assert r.returncode == 0


def test_missing_rules_file_allows_everything(tmp_path):
    r = run_hook(tmp_path, bash_event("pytest tests/", tmp_path),
                 extra_env={"KB_CONTEXT_GUARD_RULES_PATH": str(tmp_path / "nope.yaml")})
    assert r.returncode == 0


def test_malformed_rules_file_debug_line_only_with_kb_debug_hooks(tmp_path):
    bad_rules = tmp_path / "bad-rules.yaml"
    bad_rules.write_text("nonsense\n", encoding="utf-8")

    silent = run_hook(tmp_path, bash_event("echo hi", tmp_path),
                       extra_env={"KB_CONTEXT_GUARD_RULES_PATH": str(bad_rules)})
    assert silent.returncode == 0 and silent.stderr.strip() == b""

    loud = run_hook(tmp_path, bash_event("echo hi", tmp_path),
                     extra_env={"KB_CONTEXT_GUARD_RULES_PATH": str(bad_rules), "KB_DEBUG_HOOKS": "1"})
    assert loud.returncode == 0
    assert b"context-guard debug" in loud.stderr
    assert b"[context-guard BLOCK]" not in loud.stderr


# ── settings registration ────────────────────────────────────────────────────────────────────

def test_settings_registers_context_guard_without_dropping_existing_entries():
    settings_path = REPO / ".claude" / "settings.json"
    data = json.loads(settings_path.read_text(encoding="utf-8"))
    pre = data["hooks"]["PreToolUse"]

    matches = [
        entry for entry in pre
        if entry.get("matcher") == "Read|Bash"
        and any("context_guard.js" in h.get("command", "") for h in entry.get("hooks", []))
    ]
    assert len(matches) == 1

    all_commands = " ".join(h["command"] for entry in pre for h in entry.get("hooks", []))
    for expected in (
        "block_no_verify.js",
        "hard_ceiling_guard.js",
        "config_protection.js",
        "model_verify_pretooluse.js",
    ):
        assert expected in all_commands
