// @vitest-environment jsdom
/**
 * Model Audit panel (Wave-1 U9).
 *
 * What these tests pin: the panel registers itself by file drop (no shared-file edit), it renders the
 * rows the daemon reports with requested-vs-observed on screen, a MISMATCH is visually distinct from
 * an ordinary row, the best-effort pairing is disclosed rather than implied, and each degraded state
 * gets its OWN named message.
 *
 * The empty state is load-bearing here in the same way it is for the Context Lifecycle panel: the
 * hooks are inert, so on an unarmed machine the honest answer is "no rows, because nothing is armed".
 * A blank panel would read as a broken fetch, so the wording is asserted, not just the absence of rows.
 */
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { render, screen, cleanup } from '@testing-library/react';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { AGENT_PLATFORM_PANELS } from '../registry';
import { panel } from './ModelAudit.panel';

/** Paths resolve from the vitest root (`dashboard/`): under jsdom `import.meta.url` is not a file: URL. */
const REPO_ROOT = resolve(process.cwd(), '..');
/** The SAME fixture the server route's test uses — generated by the committed hooks themselves. */
const HOOK_WRITTEN_FIXTURE = resolve(REPO_ROOT, 'dashboard/server/modelAudit/__fixtures__/model-audit.jsonl');

/** The route's own shape, built from the real fixture: parsed, newest first, with the file's mtime. */
function responseFromFixture() {
  const rows = readFileSync(HOOK_WRITTEN_FIXTURE, 'utf8')
    .split(/\r?\n/)
    .filter((line) => line.trim())
    .map((line) => JSON.parse(line));
  return {
    available: true,
    auditPath: 'C:/store/model-audit.jsonl',
    modifiedAt: '2026-08-18T04:00:00.000Z',
    rows: rows.slice().reverse(),
    totalRows: rows.length,
  };
}

function mockFetch(body: unknown, status = 200) {
  return vi.fn(async (input: RequestInfo | URL) => {
    const url = String(input);
    if (url !== '/api/model-audit') throw new Error(`unexpected fetch: ${url}`);
    return { ok: status < 400, status, json: async () => body } as Response;
  });
}

beforeEach(() => {
  vi.stubGlobal('fetch', mockFetch(responseFromFixture()));
});

afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
  vi.restoreAllMocks();
});

async function renderPanel() {
  render(panel.render() as React.JSX.Element);
  return screen.findByTestId;
}

describe('ModelAudit panel', () => {
  it('registers itself in the panel registry by file drop', () => {
    expect(panel.id).toBe('model-audit');
    expect(AGENT_PLATFORM_PANELS.map((p) => p.id)).toContain('model-audit');
    const registered = AGENT_PLATFORM_PANELS.find((p) => p.id === 'model-audit');
    expect(registered?.title).toBe(panel.title);
  });

  it('renders the rows the hooks actually write, newest first', async () => {
    await renderPanel();
    const summary = await screen.findByTestId('ap-modelaudit-summary');
    expect(summary.textContent).toContain('3 rows');
    const rows = screen.getAllByTestId(/^ap-modelaudit-row-/);
    expect(rows).toHaveLength(3);
    // Newest first: the SubagentStop row leads.
    expect(rows[0].textContent).toContain('SubagentStop');
  });

  it('shows requested AND observed on a stop row, which is the whole point', async () => {
    await renderPanel();
    const mismatch = await screen.findByTestId('ap-modelaudit-row-mismatch');
    expect(mismatch.textContent).toContain('requested');
    expect(mismatch.textContent).toContain('opus');
    expect(mismatch.textContent).toContain('observed');
    expect(mismatch.textContent).toContain('claude-haiku-4-5');
  });

  it('marks a mismatch distinctly from an ordinary row', async () => {
    await renderPanel();
    const mismatch = await screen.findByTestId('ap-modelaudit-row-mismatch');
    expect(mismatch.className).toContain('ap-modelaudit__row--mismatch');
    expect(screen.getByTestId('ap-modelaudit-row-allowed').className).not.toContain('--mismatch');
    // An off-policy model is flagged too, one step softer than a mismatch.
    expect(screen.getByTestId('ap-modelaudit-row-unknown').className).toContain('ap-modelaudit__row--unknown');
  });

  it('discloses that stop rows are paired to a dispatch heuristically', async () => {
    await renderPanel();
    expect((await screen.findByTestId('ap-modelaudit-pairing')).textContent).toContain('not by a shared id');
  });

  it('says outright that a mismatch is a prompt to look, never proof', async () => {
    await renderPanel();
    const note = await screen.findByTestId('ap-modelaudit-note');
    expect(note.textContent).toContain('never proof');
    expect(note.textContent).toContain('Open the transcript before concluding');
  });

  it('shows the first-responding model as "observed", with mentions kept separate', async () => {
    const body = responseFromFixture();
    body.rows[0] = {
      ...body.rows[0],
      observed_model: 'claude-haiku-4-5',
      observed_models: ['claude-opus-5', 'claude-haiku-4-5'],
    };
    vi.stubGlobal('fetch', mockFetch(body));
    await renderPanel();
    const mismatch = await screen.findByTestId('ap-modelaudit-row-mismatch');
    expect(mismatch.textContent).toContain('observed');
    expect(mismatch.textContent).toContain('claude-haiku-4-5');
    // A merely-quoted id never reads as what ran.
    expect((await screen.findByTestId('ap-modelaudit-also-seen')).textContent).toContain('claude-opus-5');
  });

  it('shows the log mtime rather than inventing a per-row timestamp', async () => {
    await renderPanel();
    expect((await screen.findByTestId('ap-modelaudit-modified')).textContent).toContain('log last written');
    for (const row of screen.getAllByTestId(/^ap-modelaudit-row-/)) {
      expect(row.textContent).not.toContain('1970');
    }
  });

  it('says when the view is truncated, so it never reads as the whole log', async () => {
    const body = responseFromFixture();
    vi.stubGlobal('fetch', mockFetch({ ...body, totalRows: 900 }));
    await renderPanel();
    expect((await screen.findByTestId('ap-modelaudit-summary')).textContent).toContain('3 of 900 rows');
  });

  it('states the honest empty answer when nothing has been recorded — the inert-hooks state', async () => {
    vi.stubGlobal(
      'fetch',
      mockFetch({ available: false, auditPath: 'C:/store/model-audit.jsonl', modifiedAt: null, rows: [], totalRows: 0 }),
    );
    await renderPanel();
    const empty = await screen.findByTestId('ap-modelaudit-empty');
    expect(empty.textContent).toContain('No audit rows');
    expect(empty.textContent).toContain('inert until armed');
    expect(empty.textContent).toContain('docs/proposals/spawn-model-verify-hooks.md');
  });

  it('names a failed read rather than rendering an empty log', async () => {
    vi.stubGlobal('fetch', mockFetch(null, 500));
    await renderPanel();
    expect((await screen.findByTestId('ap-modelaudit-unavailable')).textContent).toContain('/api/model-audit');
    expect(screen.queryByTestId('ap-modelaudit-empty')).toBeNull();
  });

  it('shows a loading state before the fetch resolves', () => {
    vi.stubGlobal('fetch', vi.fn(() => new Promise<Response>(() => {})));
    render(panel.render() as React.JSX.Element);
    expect(screen.getByTestId('ap-modelaudit-loading')).toBeTruthy();
  });
});
