import { mkdtemp, rm, symlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { afterEach, describe, expect, it } from 'vitest';
import { collectCloudExperiment } from './cloudExperiment.ts';

const temporary: string[] = [];
async function fixture(overrides: Record<string, unknown> = {}): Promise<string> { const root = await mkdtemp(join(tmpdir(), 'figment-cloud-experiment-')); temporary.push(root); await writeFile(join(root, 'run.json'), JSON.stringify({ schema: 'figment/runpod-run@1', dry_run: false, started_utc: '2026-09-09T07:33:27+00:00', finished_utc: '2026-09-09T07:34:21+00:00', max_minutes: 60, preflight_estimate_usd: 1.3, estimated_actual_usd: 0.019366, termination_verified: true, jobs: [], artifacts: [], error: 'BootstrapFailed: bootstrap failed after 3 attempts', pod_id: 'must-not-project', uploads: [{ name: 'g01.jpg' }], bootstrap_log_tail: 'must-not-project', ...overrides })); return root; }
afterEach(async () => { await Promise.all(temporary.splice(0).map((path) => rm(path, { recursive: true, force: true }))); });

describe('cloud experiment projection', () => {
  it('refuses malformed error values instead of labeling a failed receipt completed', async () => {
    for (const error of [null, false, 7, {}, '']) {
      const root = await fixture({ error });
      expect(collectCloudExperiment(root)).toEqual({ status: 'unavailable', reason: 'evidence-unavailable' });
    }
  });
  it('distinguishes a terminal bootstrap failure from quality review and redacts sensitive run fields', async () => { const root = await fixture(); const result = collectCloudExperiment(root); expect(result).toEqual({ status: 'recorded', execution: 'failed', liveness: null, maxMinutes: 60, maxUsd: null, preflightEstimateUsd: 1.3, estimatedActualUsd: 0.019366, startedUtc: '2026-09-09T07:33:27+00:00', finishedUtc: '2026-09-09T07:34:21+00:00', terminationVerified: true, outputCount: 0, quality: 'not-reviewed', failure: 'bootstrap' }); expect(JSON.stringify(result)).not.toContain('must-not-project'); });
  it('counts validated producer job files and never ancillary artifacts as output images', async () => { const completed = await fixture({ error: undefined, jobs: [{ files: [{ path: 'seed-481516234.png', bytes: 721 }, { path: 'seed-90210.png', bytes: 722 }] }], artifacts: [{ private_path: 'not-projected' }] }); expect(collectCloudExperiment(completed)).toMatchObject({ execution: 'completed', outputCount: 2, quality: 'not-reviewed', failure: null }); });
  it('reads one producer-shaped acquired journal without mislabeling its spend cap as an estimate', async () => { const root = await mkdtemp(join(tmpdir(), 'figment-cloud-experiment-')); temporary.push(root); const podName = 'figment-bakeoff-20260909-074204-64f1e1'; const record = { schema: 'figment/pod-recovery@1', state: 'acquired', attempt_id: podName, pod_name: podName, manifest_path: join(root, 'driver-plan.json'), manifest_sha256: 'a'.repeat(64), max_minutes: 60, max_usd: 10, created_utc: '2026-09-09T07:42:04+00:00', receipt_path: join(root, 'run.json'), pod_id: 'must-not-project', absence_verified: false, intent_sha256: 'b'.repeat(64) }; await writeFile(join(root, `recovery-${podName}.json`), JSON.stringify(record)); expect(collectCloudExperiment(root)).toEqual({ status: 'recorded', execution: 'started-pending-final', liveness: 'unknown', maxMinutes: 60, maxUsd: 10, preflightEstimateUsd: null, estimatedActualUsd: null, startedUtc: '2026-09-09T07:42:04+00:00', finishedUtc: null, terminationVerified: null, outputCount: 0, quality: 'not-reviewed', failure: null }); await writeFile(join(root, 'recovery-figment-bakeoff-20260909-074205-64f1e2.json'), JSON.stringify(record)); expect(collectCloudExperiment(root)).toEqual({ status: 'unavailable', reason: 'evidence-unavailable' }); });
  it('refuses incomplete acquired journals and receipts outside the configured run directory', async () => { const root = await mkdtemp(join(tmpdir(), 'figment-cloud-experiment-')); temporary.push(root); const podName = 'figment-bakeoff-20260909-074204-64f1e1'; const path = join(root, `recovery-${podName}.json`); const record = { schema: 'figment/pod-recovery@1', state: 'acquired', attempt_id: podName, pod_name: podName, manifest_path: join(root, 'driver-plan.json'), manifest_sha256: 'a'.repeat(64), max_minutes: 60, max_usd: 10, created_utc: '2026-09-09T07:42:04+00:00', receipt_path: join(root, 'run.json'), pod_id: 'pod-1', absence_verified: false, intent_sha256: 'b'.repeat(64) }; const { pod_id: _podId, ...missingPod } = record; await writeFile(path, JSON.stringify(missingPod)); expect(collectCloudExperiment(root)).toEqual({ status: 'unavailable', reason: 'evidence-unavailable' }); await writeFile(path, JSON.stringify({ ...record, receipt_path: join(tmpdir(), 'foreign', 'run.json') })); expect(collectCloudExperiment(root)).toEqual({ status: 'unavailable', reason: 'evidence-unavailable' }); });
  it('fails closed for malformed records and reparse roots', async () => { const malformed = await fixture({ schema: 'wrong' }); expect(collectCloudExperiment(malformed)).toEqual({ status: 'unavailable', reason: 'evidence-unavailable' }); const root = await fixture(); const link = `${root}-link`; temporary.push(link); await symlink(root, link, 'junction'); expect(collectCloudExperiment(link)).toEqual({ status: 'unavailable', reason: 'evidence-unavailable' }); expect(collectCloudExperiment()).toEqual({ status: 'not-configured' }); });
});
