/** Fixed-root, read-only projection of declared generated-input experiments. */
import { createHash } from 'node:crypto';
import { closeSync, fstatSync, lstatSync, openSync, opendirSync, readSync, realpathSync } from 'node:fs';
import { isAbsolute, join, relative, resolve, sep } from 'node:path';

const MAX_ITEMS = 16, MAX_SCAN = 34, MAX_IMAGE = 8 * 1024 * 1024, MAX_TOTAL = 64 * 1024 * 1024, MAX_JSON = 128 * 1024, MAX_PIXELS = 32_000_000;
const SHA = /^[a-f0-9]{64}$/, NAME = /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}\.png$/;
const PNG = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
interface Root { path: string; real: string; }
interface Member { name: string; path: string; bytes: number; }
export interface GeneratedInput { name: string; bytes: number; sha256: string; width: number; height: number; sourceReference: string; sourceSha256: string; generatedOn: string | null; reviewStatus: string; visualReview: Record<string, string>; }
export interface GeneratedInputsProjection { available: boolean; items: GeneratedInput[]; truncated: boolean; }
export interface LoadedGeneratedInput { bytes: Buffer; width: number; height: number; }

function inside(root: string, path: string): boolean { const value = relative(root, path); return value === '' || (!value.startsWith(`..${sep}`) && value !== '..' && !isAbsolute(value)); }
function reparse(path: string): boolean { try { const info = lstatSync(path); const real = realpathSync(path); return info.isSymbolicLink() || (process.platform === 'win32' && resolve(real) !== resolve(path)); } catch { return true; } }
function root(path: string | null | undefined): Root | null { try { if (!path?.trim()) return null; const resolved = resolve(path); const info = lstatSync(resolved); const real = realpathSync(resolved); return info.isDirectory() && !reparse(resolved) ? { path: resolved, real } : null; } catch { return null; } }
function safe(root: Root, candidate: string): string | null { const path = isAbsolute(candidate) ? resolve(candidate) : resolve(root.path, candidate); if (!inside(root.path, path)) return null; try { let cursor = root.path; for (const segment of relative(root.path, path).split(/[\\/]/).filter(Boolean)) { cursor = join(cursor, segment); if (reparse(cursor)) return null; } return lstatSync(path).isFile() && inside(root.real, realpathSync(path)) ? path : null; } catch { return null; } }
function bounded(path: string, limit: number, expected?: number): Buffer | null { let fd: number | null = null; try { fd = openSync(path, 'r'); const before = fstatSync(fd); if (!before.isFile() || before.size < 1 || before.size > limit || (expected !== undefined && before.size !== expected)) return null; const data = Buffer.allocUnsafe(before.size); for (let offset = 0; offset < data.length;) { const count = readSync(fd, data, offset, data.length - offset, offset); if (count <= 0) return null; offset += count; } const after = fstatSync(fd); return after.isFile() && after.size === before.size && (expected === undefined || after.size === expected) ? data : null; } catch { return null; } finally { if (fd !== null) try { closeSync(fd); } catch { /* fail closed above */ } } }
function png(data: Buffer): { width: number; height: number } | null { if (data.length < 33 || !data.subarray(0, 8).equals(PNG) || data.readUInt32BE(8) !== 13 || data.subarray(12, 16).toString('ascii') !== 'IHDR') return null; const width = data.readUInt32BE(16), height = data.readUInt32BE(20); return width > 0 && height > 0 && width * height <= MAX_PIXELS ? { width, height } : null; }
function text(value: unknown, limit: number): string | null { return typeof value === 'string' && value.length > 0 && value.length <= limit ? value : null; }
function record(data: Buffer, name: string, image: Buffer, info: { width: number; height: number }, canonicalSha: string): GeneratedInput | null { try { const value: unknown = JSON.parse(data.toString('utf8')); if (typeof value !== 'object' || value === null || Array.isArray(value)) return null; const row = value as Record<string, unknown>, output = row.output as Record<string, unknown>, source = row.source as Record<string, unknown>, generation = row.generation as Record<string, unknown>, review = row.review as Record<string, unknown>; if (row.schema !== 'figment/generated-input-experiment@1' || row.creator !== 'creator-001' || !output || !source || !generation || !review || output.file !== name || output.sha256 !== createHash('sha256').update(image).digest('hex') || (output.bytes !== undefined && output.bytes !== image.length) || source.reference !== 'anchors/g01.jpg' || source.sha256 !== canonicalSha) return null; const status = text(review.status, 128); if (status === null) return null; const visual: Record<string, string> = {}; for (const key of ['adult_presentation', 'clothing', 'identity', 'realism', 'coverage', 'independent_findings']) { const item = text(review[key], 512); if (item !== null) visual[key] = item; } const date = typeof generation.date === 'string' && generation.date.length <= 32 ? generation.date : null; return { name, bytes: image.length, sha256: createHash('sha256').update(image).digest('hex'), ...info, sourceReference: 'anchors/g01.jpg', sourceSha256: canonicalSha, generatedOn: date, reviewStatus: status, visualReview: visual }; } catch { return null; } }
function members(configuredRoot: string | null | undefined, canonicalSha: string): { root: Root; members: Member[]; truncated: boolean } | null { const opened = root(configuredRoot); if (opened === null || !SHA.test(canonicalSha)) return null;
  // The canonical hash is freshly read from the fixed Figment persona root by the caller.
  const entries: import('node:fs').Dirent[] = []; try { const dir = opendirSync(opened.path); try { let entry = dir.readSync(); while (entry !== null && entries.length < MAX_SCAN) { entries.push(entry); entry = dir.readSync(); } if (entry !== null) return null; const truncated = false; const selected: Member[] = []; let total = 0; for (const entry of entries.filter((item) => item.isFile() && item.name.endsWith('.provenance.json')).sort((a, b) => a.name.localeCompare(b.name))) { const name = entry.name.slice(0, -'.provenance.json'.length) + '.png'; if (!NAME.test(name)) continue; const imagePath = safe(opened, name), provenancePath = safe(opened, entry.name); if (!imagePath || !provenancePath) continue; const image = bounded(imagePath, MAX_IMAGE); const provenance = bounded(provenancePath, MAX_JSON); const info = image === null ? null : png(image); const parsed = image === null || provenance === null || info === null || total + image.length > MAX_TOTAL ? null : record(provenance, name, image, info, canonicalSha); if (parsed === null) continue; if (selected.length >= MAX_ITEMS) return { root: opened, members: selected, truncated: true }; selected.push({ name, path: imagePath, bytes: image!.length }); total += image!.length; } return { root: opened, members: selected, truncated }; } finally { dir.closeSync(); } } catch { return null; } }
function canonicalHash(repoRoot: string): string | null { const repo = root(join(repoRoot, 'orgs', 'figment')); if (repo === null) return null; const path = safe(repo, 'personas/creator-001/anchors/g01.jpg'); const data = path === null ? null : bounded(path, MAX_IMAGE); return data === null ? null : createHash('sha256').update(data).digest('hex'); }
export function collectGeneratedInputs(repoRoot: string, configuredRoot: string | null | undefined): GeneratedInputsProjection { const hash = canonicalHash(repoRoot); if (hash === null) return { available: false, items: [], truncated: false }; const listed = members(configuredRoot, hash); if (listed === null) return { available: false, items: [], truncated: false }; const items: GeneratedInput[] = []; for (const member of listed.members) { const data = bounded(member.path, MAX_IMAGE, member.bytes), info = data === null ? null : png(data); const provenance = safe(listed.root, `${member.name.slice(0, -4)}.provenance.json`); const raw = provenance === null ? null : bounded(provenance, MAX_JSON); if (data && info && raw) { const item = record(raw, member.name, data, info, hash); if (item) items.push(item); } } return { available: true, items, truncated: listed.truncated }; }
function requestedMember(configuredRoot: string | null | undefined, canonicalSha: string, name: string): { root: Root; member: Member } | null {
  const opened = root(configuredRoot); if (opened === null || !SHA.test(canonicalSha) || !NAME.test(name)) return null;
  const provenanceName = `${name.slice(0, -4)}.provenance.json`; let present = false;
  try { const dir = opendirSync(opened.path); try {
    let entry = dir.readSync(); let attempts = 0;
    while (entry !== null && attempts < MAX_SCAN) { attempts += 1; if (entry.isFile() && entry.name === provenanceName) present = true; entry = dir.readSync(); }
    if (entry !== null || !present) return null;
  } finally { dir.closeSync(); } } catch { return null; }
  const imagePath = safe(opened, name), provenancePath = safe(opened, provenanceName);
  if (imagePath === null || provenancePath === null) return null;
  const image = bounded(imagePath, MAX_IMAGE), provenance = bounded(provenancePath, MAX_JSON), info = image === null ? null : png(image);
  if (image === null || provenance === null || info === null || record(provenance, name, image, info, canonicalSha) === null) return null;
  return { root: opened, member: { name, path: imagePath, bytes: image.length } };
}

/** Binary reads enumerate bounded names but open/hash only the requested pair and PNG. */
export function readGeneratedInput(repoRoot: string, configuredRoot: string | null | undefined, name: string, expectedSha256: string): LoadedGeneratedInput | null {
  if (!NAME.test(name) || !SHA.test(expectedSha256)) return null;
  const hash = canonicalHash(repoRoot); if (hash === null) return null;
  const selected = requestedMember(configuredRoot, hash, name); if (selected === null) return null;
  const data = bounded(selected.member.path, MAX_IMAGE, selected.member.bytes), info = data === null ? null : png(data);
  return data && info && createHash('sha256').update(data).digest('hex') === expectedSha256 ? { bytes: data, ...info } : null;
}
