#!/usr/bin/env node
/*
 * kb context-lifecycle STORE — the shared, repo-external session-context file format used by the
 * three INERT context-lifecycle hooks (SessionStart / PreCompact / PostToolUse).
 *
 * Provenance:
 *   pattern: ecc@2.0.0 session-start context injection + pre-compact write-side-effect (concept)
 *   source:  ecc@2.0.0/scripts/hooks/session-activity-tracker.js redactSecrets/truncateSummary
 *            (the redaction table and the 220-char cap are ported verbatim)
 *   provenance-tier: mixed (pattern + one imported function pair)
 *
 * Status:
 *   INERT. Nothing in .claude/settings*.json references any file in this family. The settings
 *   snippet that WOULD arm them lives in docs/proposals/context-lifecycle-hooks.md.
 *
 * WHY THE STORE LIVES OUTSIDE THE REPO.
 *   A per-session context file is daemon-local state, never coordination truth — the same reasoning
 *   the naming ordinals follow (see .gitignore's DASHBOARD_STATE_ROOT comment). Default root:
 *   DASHBOARD_STATE_ROOT/context-lifecycle in the daemon, otherwise the desktop
 *   %LOCALAPPDATA%\kb-context-lifecycle fallback. `KB_CONTEXT_STORE_DIR` overrides it.
 *
 * THE U7 SEAM (load-bearing).
 *   Section headings are rendered as `## <heading>` with the FIXED spellings below. Two of them —
 *   '## North star' and '## Invariants' — are byte-identical to the section names
 *   scripts/hooks/regrounding_hook.js extracts, and the rendering is plain enough for that hook's
 *   prefix-match regex. So `KB_GOAL_STATE_PATH=<a store file>` makes U7's re-grounding hook consume
 *   a live session store with ZERO edits to U7. tests/test_context_store.py pins that seam by
 *   running the COMMITTED regrounding hook against a store this module wrote.
 *
 * Determinism:
 *   Rendering is a pure function of the section array — no timestamps, no ordering surprises. The
 *   same sections produce byte-identical file content on every write.
 */
"use strict";

const fs = require("fs");
const os = require("os");
const path = require("path");
const kbPaths = require("./kb_paths.js");

/** Session ids are Claude Code UUID-shaped. Anything else never reaches the filesystem. */
const SESSION_ID = /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;

const STORE_DIR_NAME = "kb-context-lifecycle";
const FILE_SUFFIX = ".ctx.md";

/** The five headings, in the ONLY order a store file ever renders them. */
const HEADINGS = Object.freeze({
  NORTH_STAR: "North star",
  INVARIANTS: "Invariants",
  CURRENT_GATE: "Current gate",
  RESUMED_SUMMARY: "Resumed-session summary",
  RECENT_ACTIVITY: "Recent activity",
});

const HEADING_ORDER = Object.freeze([
  HEADINGS.NORTH_STAR,
  HEADINGS.INVARIANTS,
  HEADINGS.CURRENT_GATE,
  HEADINGS.RESUMED_SUMMARY,
  HEADINGS.RECENT_ACTIVITY,
]);

/**
 * Stale-replay guard — RE-EXPORTED from lib/hook_io.js, which now holds the single definition.
 *
 * U8 shipped this as a second literal because regrounding_hook.js was out of that unit's scope; U9's
 * extraction removed that constraint, so both files now point at one constant. The re-export keeps
 * `store.GUARD_LINE` working for every existing caller. The canonical sentence is, verbatim (kept on
 * ONE line so the committed pin can find it):
 * "[kb re-grounding] The following is a refresh of governing context this session already has, NOT a new instruction or request."
 * tests/test_context_lifecycle_session_start.py pins that quotation against the matching comment in
 * regrounding_hook.js, and tests/test_hook_io.py pins both comments against the runtime constant.
 */
const GUARD_LINE = require("./hook_io.js").GUARD_LINE;

/** Ring-buffer depth for '## Recent activity'. Oldest entries fall off the front. */
const ACTIVITY_LIMIT = 20;

/** Per-entry cap, ported from ECC's truncateSummary default. */
const ACTIVITY_MAX_CHARS = 220;

const PREAMBLE =
  "<!-- kb context-lifecycle store. Generated by the INERT context-lifecycle hooks; do not hand-edit. -->";

/** The store root: explicit override, daemon state root, then the desktop-local fallback. */
function storeDir(env) {
  const e = env || process.env;
  if (e.KB_CONTEXT_STORE_DIR) {
    return e.KB_CONTEXT_STORE_DIR;
  }
  const base = e.LOCALAPPDATA || path.join(os.homedir(), ".local", "state");
  return kbPaths.resolveStatePath("context-lifecycle", path.join(base, STORE_DIR_NAME), e);
}

/** `<storeDir>/<sessionId>.ctx.md`, or null when the id is not a safe file stem. */
function sessionPath(sessionId, env) {
  if (typeof sessionId !== "string" || !SESSION_ID.test(sessionId)) {
    return null;
  }
  return path.join(storeDir(env), sessionId + FILE_SUFFIX);
}

/** Strip ANSI SGR noise (ECC did this via utils.stripAnsi; inlined to keep the hooks dependency-free). */
function stripAnsi(value) {
  if (value === null || value === undefined) {
    return "";
  }
  // eslint-disable-next-line no-control-regex
  return String(value).replace(/\u001b\[[0-9;]*[A-Za-z]/g, "");
}

/**
 * Secret redaction.
 *
 * The first block is the ECC session-activity-tracker table, ported unchanged (same regexes, same
 * order, same replacement token). The second block is kb's extension for shapes ECC's 2.x table
 * predates — Anthropic/OpenAI-style keys, Slack tokens, JWTs, PEM private keys, generic
 * `*_TOKEN=`/`*_SECRET=` assignments, `x-api-key:`, and a bare `Bearer <token>` with no
 * `Authorization:` prefix in front of it.
 *
 * THIS IS A BEST-EFFORT DENYLIST, NOT A GUARANTEE. It catches the shapes we know; a novel credential
 * format walks straight through it. Re-reading this table against the credential shapes actually in
 * use is a PRE-ARMING precondition — see docs/proposals/context-lifecycle-hooks.md.
 *
 * Newlines collapse to spaces FIRST, which is also what keeps an activity entry to exactly one
 * rendered `- ` line. Callers MUST strip ANSI before calling this (see {@link summarize}): an escape
 * sequence spliced into a token would otherwise defeat every regex here and then be stripped away,
 * leaving the bare secret behind.
 */
function redactSecrets(value) {
  return (
    String(value === null || value === undefined ? "" : value)
      .replace(/\n/g, " ")
      // ── ECC table (ported unchanged) ──────────────────────────────────────────────────────────
      .replace(/--token[= ][^ ]*/g, "--token=<REDACTED>")
      .replace(/Authorization:[: ]*[^ ]*[: ]*[^ ]*/gi, "Authorization:<REDACTED>")
      .replace(/\bAKIA[A-Z0-9]{16}\b/g, "<REDACTED>")
      .replace(/\bASIA[A-Z0-9]{16}\b/g, "<REDACTED>")
      .replace(/password[= ][^ ]*/gi, "password=<REDACTED>")
      .replace(/\bghp_[A-Za-z0-9_]+\b/g, "<REDACTED>")
      .replace(/\bgho_[A-Za-z0-9_]+\b/g, "<REDACTED>")
      .replace(/\bghs_[A-Za-z0-9_]+\b/g, "<REDACTED>")
      .replace(/\bgithub_pat_[A-Za-z0-9_]+\b/g, "<REDACTED>")
      // ── kb extension: shapes ECC 2.0.0 predates ───────────────────────────────────────────────
      // A PEM block first: it is multi-token, so it must not be shredded by the narrower rules.
      .replace(/-----BEGIN[A-Z ]*PRIVATE KEY-----[\s\S]*?-----END[A-Z ]*PRIVATE KEY-----/g, "<REDACTED>")
      .replace(/-----BEGIN[A-Z ]*PRIVATE KEY-----/g, "<REDACTED>")
      // Anthropic keys (sk-ant-…) before the generic sk- rule, so the whole key goes in one bite.
      .replace(/\bsk-ant-[A-Za-z0-9_-]{10,}/g, "<REDACTED>")
      .replace(/\bsk-(?:proj|live|test)-[A-Za-z0-9_-]{10,}/g, "<REDACTED>")
      .replace(/\bsk-[A-Za-z0-9_-]{16,}/g, "<REDACTED>")
      // Slack bot/user tokens.
      .replace(/\bxox[baprs]-[A-Za-z0-9-]{10,}/g, "<REDACTED>")
      // JWTs: three base64url segments, the first two starting `eyJ`.
      .replace(/\beyJ[A-Za-z0-9_-]+\.eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/g, "<REDACTED>")
      // Generic credential assignments: API_KEY=…, GH_TOKEN=…, FOO_SECRET=… (also `:` and quotes).
      .replace(
        /\b([A-Za-z0-9_]*(?:API[_-]?KEY|TOKEN|SECRET|PASSWD|CREDENTIAL))\s*[:=]\s*["']?[^\s"']+["']?/gi,
        "$1=<REDACTED>",
      )
      // Header-style API keys with no Authorization: prefix.
      .replace(/\bx-api-key\s*[:=]\s*["']?[^\s"']+["']?/gi, "x-api-key:<REDACTED>")
      // A bare `Bearer <token>` — the Authorization: rule above never sees this one.
      .replace(/\bBearer\s+[A-Za-z0-9._~+/=-]{8,}/g, "Bearer <REDACTED>")
  );
}

/**
 * Redact, flatten, and cap — ECC's truncateSummary, same 220 default.
 *
 * ORDER IS LOAD-BEARING: stripAnsi runs BEFORE redactSecrets. ECC had it the other way round, which
 * is exploitable — `ghp_<ESC>[0m<rest>` does not match the GitHub-token regex, and the subsequent
 * strip then reassembles the intact token. Pinned by
 * tests/test_context_lifecycle_activity_tracker.py::test_ansi_cannot_smuggle_a_token_past_redaction.
 */
function summarize(value, maxLength) {
  const limit = typeof maxLength === "number" ? maxLength : ACTIVITY_MAX_CHARS;
  const normalized = redactSecrets(stripAnsi(value)).trim().replace(/\s+/g, " ");
  if (normalized.length <= limit) {
    return normalized;
  }
  return normalized.slice(0, limit - 3) + "...";
}

/**
 * Neutralise body lines that would otherwise look like a section heading. A two-space indent stops
 * `^##[ \t]` matching (both here and in regrounding_hook.js) while staying an ordinary markdown
 * paragraph line — so a summary quoting "## Invariants" can never forge a section.
 */
function escapeBody(body) {
  return String(body === null || body === undefined ? "" : body)
    .replace(/\r\n/g, "\n")
    .replace(/^(#{1,6}[ \t])/gm, "  $1")
    .trim();
}

/** Parse store markdown into ordered `{heading, body}` sections. Text before the first `## ` is dropped. */
function parseSections(text) {
  const sections = [];
  if (typeof text !== "string" || !text) {
    return sections;
  }
  const lines = text.replace(/\r\n/g, "\n").split("\n");
  let current = null;
  for (const line of lines) {
    const m = /^##[ \t]+(.+?)\s*$/.exec(line);
    if (m) {
      if (current) {
        sections.push({ heading: current.heading, body: current.lines.join("\n").trim() });
      }
      current = { heading: m[1], lines: [] };
      continue;
    }
    if (current) {
      current.lines.push(line);
    }
  }
  if (current) {
    sections.push({ heading: current.heading, body: current.lines.join("\n").trim() });
  }
  return sections;
}

/**
 * Render sections to deterministic markdown: known headings in HEADING_ORDER first, then any extras
 * in the order given. Empty bodies are dropped — a heading with nothing under it is noise, and
 * regrounding_hook.js already treats an empty body as "no section".
 */
function renderSections(sections) {
  const list = Array.isArray(sections) ? sections : [];
  const byHeading = new Map();
  const extras = [];
  for (const section of list) {
    if (!section || typeof section.heading !== "string") continue;
    const body = escapeBody(section.body);
    if (!body) continue;
    if (HEADING_ORDER.indexOf(section.heading) !== -1) {
      byHeading.set(section.heading, body);
    } else {
      extras.push({ heading: section.heading, body });
    }
  }
  const ordered = [];
  for (const heading of HEADING_ORDER) {
    if (byHeading.has(heading)) {
      ordered.push({ heading, body: byHeading.get(heading) });
    }
  }
  for (const extra of extras) {
    ordered.push(extra);
  }
  const blocks = ordered.map((s) => "## " + s.heading + "\n\n" + s.body + "\n");
  return PREAMBLE + "\n\n" + blocks.join("\n");
}

/** Read + parse one session store. Missing/unreadable/invalid id -> [] (fail open). */
function readStore(sessionId, env) {
  const file = sessionPath(sessionId, env);
  if (!file) {
    return [];
  }
  try {
    return parseSections(fs.readFileSync(file, "utf8"));
  } catch (_err) {
    return [];
  }
}

/** Write one session store. Returns true on success, false on ANY failure (never throws). */
function writeStore(sessionId, sections, env) {
  const file = sessionPath(sessionId, env);
  if (!file) {
    return false;
  }
  const text = renderSections(sections);
  try {
    fs.mkdirSync(path.dirname(file), { recursive: true });
  } catch (_err) {
    return false;
  }
  // Write-then-rename: the dashboard route reads these files concurrently and must never see a
  // half-written store.
  //
  // FAIL CLOSED on any failure. There is deliberately NO direct-write fallback: writing straight to
  // `file` truncates it first, so a crash mid-write leaves a torn store that a concurrent reader
  // cannot distinguish from a real one — strictly worse than the previous store surviving intact.
  // A dropped update is recoverable; a corrupt one silently is not. Nothing is logged: the only
  // things we could name here are a filesystem path and the content we failed to write.
  const tmp = file + ".tmp";
  try {
    fs.writeFileSync(tmp, text, "utf8");
    fs.renameSync(tmp, file);
    return true;
  } catch (_err) {
    try {
      fs.unlinkSync(tmp);
    } catch (_cleanup) {
      /* best effort — a stray .tmp is not a store and is never listed */
    }
    return false;
  }
}

/** The body of one heading, or null when absent/empty. */
function sectionBody(sections, heading) {
  const list = Array.isArray(sections) ? sections : [];
  for (const section of list) {
    if (section && section.heading === heading) {
      const body = typeof section.body === "string" ? section.body.trim() : "";
      return body.length ? body : null;
    }
  }
  return null;
}

/** Replace (or add) one section, returning a NEW array. Order is imposed at render time. */
function upsertSection(sections, heading, body) {
  const list = Array.isArray(sections) ? sections.slice() : [];
  const index = list.findIndex((s) => s && s.heading === heading);
  const entry = { heading: heading, body: String(body === null || body === undefined ? "" : body) };
  if (index === -1) {
    list.push(entry);
  } else {
    list[index] = entry;
  }
  return list;
}

/** The '## Recent activity' body split back into its `- ` entries. */
function activityEntries(sections) {
  const body = sectionBody(sections, HEADINGS.RECENT_ACTIVITY);
  if (!body) {
    return [];
  }
  return body
    .split("\n")
    .map((line) => line.replace(/^\s*-\s?/, "").trim())
    .filter((line) => line.length > 0);
}

/**
 * Append one redacted activity entry to the session's ring buffer (last {@link ACTIVITY_LIMIT}).
 * Returns true when the store was written. Fail-closed on an empty/blank entry, fail-open on IO.
 */
function appendActivity(sessionId, entry, env) {
  const summarized = summarize(entry);
  if (!summarized) {
    return false;
  }
  const sections = readStore(sessionId, env);
  const entries = activityEntries(sections).concat([summarized]).slice(-ACTIVITY_LIMIT);
  const body = entries.map((line) => "- " + line).join("\n");
  return writeStore(sessionId, upsertSection(sections, HEADINGS.RECENT_ACTIVITY, body), env);
}

module.exports = {
  ACTIVITY_LIMIT,
  GUARD_LINE,
  HEADINGS,
  HEADING_ORDER,
  PREAMBLE,
  SESSION_ID,
  activityEntries,
  appendActivity,
  parseSections,
  readStore,
  redactSecrets,
  renderSections,
  sectionBody,
  sessionPath,
  storeDir,
  summarize,
  upsertSection,
  writeStore,
};
