from __future__ import annotations
import argparse
import gzip
import hashlib
import io
import json
import sys
import tarfile
from pathlib import Path

if __package__ in {None, ""}:  # direct `python scripts/build_platform_release.py` execution
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from deploy.control_plane_schema import (
    RELEASE_ATTESTATION_KEYS,
    RELEASE_ATTESTATION_SCHEMA,
    ROLLBACK_STATE_SCHEMA,
    STATE_MIGRATION,
    STATE_SCHEMA,
)

RELEASE_ROOTS = (
    "dashboard/dist", "dashboard/server", "dashboard/src", "dashboard/node_modules",
    "dashboard/package.json", "dashboard/package-lock.json",
    "dashboard/config/repositories.json", "scripts", "schemas", "deploy",
)
ATTESTED_SCHEDULE_SOURCES = (
    "HEARTBEAT.md",
    "orgs/*/HEARTBEAT.md",
    "agents/*.md",
)
NATIVE_BUILD_KEEP_SUFFIXES = {".node", ".dll", ".so", ".dylib", ".exe"}


def _node_gyp_build_roots(source: Path) -> set[Path]:
    """Find only build trees generated by node-gyp, using its config.gypi discriminator."""
    modules = source / "dashboard/node_modules"
    if not modules.is_dir():
        return set()
    return {
        marker.parent
        for marker in modules.rglob("build/config.gypi")
        if marker.is_file() and marker.parent.name == "build"
    }


def _is_node_gyp_intermediate(item: Path, build_roots: set[Path]) -> bool:
    """Exclude path-bearing node-gyp intermediates while retaining loadable native binaries.

    Published JavaScript packages also use directories named ``build``; unlike node-gyp output,
    those directories do not contain config.gypi and must remain in the release.
    """
    if not any(root in item.parents for root in build_roots):
        return False
    return item.suffix.lower() not in NATIVE_BUILD_KEEP_SUFFIXES


def release_files(source: Path) -> list[Path]:
    files: list[Path] = []
    build_roots = _node_gyp_build_roots(source)
    for rel in RELEASE_ROOTS:
        path = source / rel
        if not path.exists():
            raise FileNotFoundError(rel)
        candidates = [path] if path.is_file() else path.rglob("*")
        files.extend(
            sorted(
                item
                for item in candidates
                if item.is_file()
                and "__pycache__" not in item.relative_to(source).parts
                and item.suffix not in {".pyc", ".pyo"}
                and not _is_node_gyp_intermediate(item, build_roots)
            )
        )
    for pattern in ATTESTED_SCHEDULE_SOURCES:
        matches = sorted(path for path in source.glob(pattern) if path.is_file())
        if not matches:
            raise FileNotFoundError(pattern)
        files.extend(matches)
    return sorted(set(files), key=lambda item: item.relative_to(source).as_posix())


def build_release(source: Path, version: str, output: Path, attestation: Path) -> None:
    if len(version) != 40 or any(char not in "0123456789abcdef" for char in version):
        raise ValueError("version must be a full lowercase git commit")
    expected_name = f"kb-platform-{version}.tar.gz"
    if output.name != expected_name:
        raise ValueError(f"release archive must be named {expected_name}")
    files = release_files(source)
    manifest = "".join(f"{hashlib.sha256(path.read_bytes()).hexdigest()}  {path.relative_to(source).as_posix()}\n" for path in files)
    with output.open("wb") as raw, gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0) as compressed, tarfile.open(fileobj=compressed, mode="w", format=tarfile.PAX_FORMAT) as archive:
        for name, data in (("VERSION", version + "\n"), ("MANIFEST.sha256", manifest)):
            info = tarfile.TarInfo(name); info.size = len(data.encode()); info.mtime = 0; info.mode = 0o444
            archive.addfile(info, io.BytesIO(data.encode()))
        for path in files:
            data = path.read_bytes()
            info = tarfile.TarInfo(path.relative_to(source).as_posix()); info.size = len(data); info.mtime = 0; info.mode = 0o555 if path.stat().st_mode & 0o111 else 0o444
            archive.addfile(info, io.BytesIO(data))
    statement = {
        "archive": output.name,
        "schema": RELEASE_ATTESTATION_SCHEMA,
        "sha256": hashlib.sha256(output.read_bytes()).hexdigest(),
        "sourceCommit": version,
        "stateSchema": STATE_SCHEMA,
        "rollbackStateSchema": ROLLBACK_STATE_SCHEMA,
        "stateMigration": STATE_MIGRATION,
        "workflow": "kb-platform-release",
    }
    if set(statement) != set(RELEASE_ATTESTATION_KEYS):
        raise RuntimeError("release attestation keys do not match registry")
    attestation.write_text(json.dumps(statement, sort_keys=True, separators=(",", ":")) + "\n", encoding="utf-8", newline="")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--version", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--attestation", type=Path, required=True)
    args = parser.parse_args(); build_release(args.source, args.version, args.output, args.attestation); return 0


if __name__ == "__main__":
    raise SystemExit(main())
