"""Mirror main-authored, daemon-read directories onto the `ops` branch.

The kb-dashboard daemon reads `agents/` and every `orgs/*/workflows/` tree from
its ops-branch worktree, but that content is authored and merged on `main`. Left
alone, ops silently drifts behind main (this happened twice, fixed by hand as ops
commits a93a140 and 63b1922). This script makes the mirror a repeatable operation
modelled on the trusted `scripts/sync_skills.py` pattern:

  * `--check` — read-only drift report (exit nonzero on drift). Compares main
    against the on-disk ops checkout when it exists, else against `origin/ops`
    directly so it is safe to run from the cloud with no worktree present.
  * default / `--sync` — in the ops worktree, follow the constitution's ops-write
    protocol (pull --rebase, checkout main content, commit-if-changed, push, retry
    once) to bring ops back in line with main. Never deletes ops-only files unless
    `--prune` is passed.

Adding another daemon-read directory later is a one-line edit to DAEMON_READ_DIRS.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

# --- Config -----------------------------------------------------------------
# Directories the daemon reads from its ops worktree but that are authored on
# main. Trailing "/" marks a directory prefix; "*" matches exactly one path
# segment. Add a new daemon-read dir here and every mode picks it up.
DAEMON_READ_DIRS = [
    "agents/",
    "orgs/*/workflows/",
]

DEFAULT_OPS_ROOT = Path(r"C:\Users\danie\kb-worktrees\dashboard-ops")
DEFAULT_MAIN_REF = "origin/main"
DEFAULT_OPS_REF = "origin/ops"

COMMIT_MSG = (
    "chore(ops): mirror daemon-read dirs from main (agents + workflows)\n\n"
    "Generated by scripts/sync_daemon_dirs.py --sync."
)


# --- Path matching ----------------------------------------------------------
def _pattern_to_regex(pattern: str) -> re.Pattern[str]:
    """Compile a DAEMON_READ_DIRS entry into a file-path matcher.

    Trailing "/" is a directory prefix (files strictly under it match); "*"
    matches exactly one path segment. So ``orgs/*/workflows/`` matches
    ``orgs/faceless-youtube/workflows/segments/seg.js`` but not
    ``orgs/faceless-youtube/STATE.md``.
    """
    body = re.escape(pattern.rstrip("/")).replace(r"\*", "[^/]+")
    return re.compile("^" + body + "/.+$")


def _compile(patterns: list[str]) -> list[re.Pattern[str]]:
    return [_pattern_to_regex(p) for p in patterns]


def _matches(path: str, matchers: list[re.Pattern[str]]) -> bool:
    return any(m.match(path) for m in matchers)


def _pattern_depth(pattern: str) -> int:
    """Segment count of a pattern's directory prefix (``orgs/*/workflows`` -> 3)."""
    return pattern.rstrip("/").count("/") + 1


# --- Git plumbing -----------------------------------------------------------
def _git(cwd: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", str(cwd), *args],
        capture_output=True,
        text=True,
        check=check,
    )


def _list_ref(repo_root: Path, ref: str, matchers: list[re.Pattern[str]]) -> dict[str, str]:
    """Return ``{path: blob_sha}`` for daemon-read files present in ``ref``.

    Uses ``git ls-tree`` so no checkout is needed and comparison is line-ending
    immune (git blob ids are computed over the normalized stored bytes).
    """
    out = _git(repo_root, "ls-tree", "-r", "-z", ref).stdout
    files: dict[str, str] = {}
    for entry in out.split("\0"):
        if not entry:
            continue
        meta, _, path = entry.partition("\t")
        parts = meta.split()
        if len(parts) < 3 or parts[1] != "blob":
            continue
        if _matches(path, matchers):
            files[path] = parts[2]
    return files


def _read_ref_blob(repo_root: Path, ref: str, path: str) -> bytes:
    return subprocess.run(
        ["git", "-C", str(repo_root), "show", f"{ref}:{path}"],
        capture_output=True,
        check=True,
    ).stdout
