"""Mirror main-authored, daemon-read directories onto the `ops` branch.

The kb-dashboard daemon reads `agents/` and every `orgs/*/workflows/` tree from
its ops-branch worktree, but that content is authored and merged on `main`. Left
alone, ops silently drifts behind main (this happened twice, fixed by hand as ops
commits a93a140 and 63b1922). This script makes the mirror a repeatable operation
modelled on the trusted `scripts/sync_skills.py` pattern:

  * `--check` — read-only drift report (exit nonzero on drift). Compares main
    against the on-disk ops checkout when it exists, else against `origin/ops`
    directly so it is safe to run from the cloud with no worktree present.
  * default / `--sync` — in the ops worktree, follow the constitution's ops-write
    protocol (pull --rebase, checkout main content, commit-if-changed, push, retry
    once) to bring ops back in line with main. Never deletes ops-only files unless
    `--prune` is passed.

Adding another daemon-read directory later is a one-line edit to DAEMON_READ_DIRS.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

# --- Config -----------------------------------------------------------------
# Directories the daemon reads from its ops worktree but that are authored on
# main. Trailing "/" marks a directory prefix; "*" matches exactly one path
# segment. Add a new daemon-read dir here and every mode picks it up.
DAEMON_READ_DIRS = [
    "agents/",
    "orgs/*/workflows/",
]

DEFAULT_OPS_ROOT = Path(r"C:\Users\danie\kb-worktrees\dashboard-ops")
DEFAULT_MAIN_REF = "origin/main"
DEFAULT_OPS_REF = "origin/ops"

COMMIT_MSG = (
    "chore(ops): mirror daemon-read dirs from main (agents + workflows)\n\n"
    "Generated by scripts/sync_daemon_dirs.py --sync."
)
