import { useEffect, useState } from 'react';
import './figment.css';

type ReviewState = 'unreviewed' | 'stale' | 'approved' | 'unknown';
type MachineGateState = 'current' | 'stale' | null;
interface RecordRow { path: string; type: string; creator: string | null; reviewState: ReviewState; machineGateState: MachineGateState; schema: string | null; }
interface Projection { schema: 'figment/hub@1'; available: boolean; creators: Array<{ id: string; persona: 'valid' | 'malformed'; loraTier: string | null; loraTrigger: string | null; accountTiers: string[] }>; creatorsTruncated: boolean; records: RecordRow[]; recordsTruncated: boolean; research: { available: boolean; artifacts: Array<{ area: 'research' | 'book'; name: string; bytes: number; modifiedAt: string }>; truncated: boolean }; diagnostic: { status: 'not-configured' } | { status: 'unavailable'; reason: string } | { status: 'diagnostic-not-promotable'; dryRun: boolean | null; podId: string | null; artifacts: Array<{ name: string; bytes: number; modifiedAt: string }> }; }
type Tab = 'creators' | 'records' | 'research';
const states = new Set<ReviewState>(['unreviewed', 'stale', 'approved', 'unknown']);
const object = (value: unknown): value is Record<string, unknown> => !!value && typeof value === 'object' && !Array.isArray(value);
const string = (value: unknown): value is string => typeof value === 'string';
const nullableString = (value: unknown): value is string | null => value === null || string(value);
const finite = (value: unknown): value is number => typeof value === 'number' && Number.isFinite(value) && value >= 0;
const bounded = (value: unknown): value is unknown[] => Array.isArray(value) && value.length <= 512;
function valid(value: unknown): Projection | null {
  if (!object(value) || value.schema !== 'figment/hub@1' || typeof value.available !== 'boolean' || !bounded(value.creators) || typeof value.creatorsTruncated !== 'boolean' || !bounded(value.records) || typeof value.recordsTruncated !== 'boolean' || !object(value.research) || typeof value.research.available !== 'boolean' || !bounded(value.research.artifacts) || typeof value.research.truncated !== 'boolean' || !object(value.diagnostic)) return null;
  if (!value.creators.every((row) => object(row) && string(row.id) && (row.persona === 'valid' || row.persona === 'malformed') && nullableString(row.loraTier) && nullableString(row.loraTrigger) && bounded(row.accountTiers) && row.accountTiers.every(string))) return null;
  if (!value.records.every((row) => object(row) && string(row.path) && string(row.type) && nullableString(row.creator) && nullableString(row.schema) && states.has(row.reviewState as ReviewState) && (row.machineGateState === null || row.machineGateState === 'current' || row.machineGateState === 'stale'))) return null;
  if (!value.research.artifacts.every((row) => object(row) && (row.area === 'research' || row.area === 'book') && string(row.name) && finite(row.bytes) && string(row.modifiedAt) && Number.isFinite(Date.parse(row.modifiedAt)))) return null;
  const d = value.diagnostic;
  if (!(d.status === 'not-configured' || d.status === 'unavailable' && string(d.reason) || d.status === 'diagnostic-not-promotable' && (typeof d.dryRun === 'boolean' || d.dryRun === null) && nullableString(d.podId) && bounded(d.artifacts) && d.artifacts.every((row) => object(row) && string(row.name) && finite(row.bytes) && string(row.modifiedAt) && Number.isFinite(Date.parse(row.modifiedAt))))) return null;
  return value as unknown as Projection;
}
function bytes(value: number): string { return value < 1024 ? `${value} B` : value < 1048576 ? `${Math.round(value / 1024)} KB` : `${(value / 1048576).toFixed(1)} MB`; }
function approval(state: ReviewState): string { return state === 'approved' ? 'Approved' : state === 'stale' ? 'Stale' : state === 'unreviewed' ? 'Unreviewed' : 'Approval unknown'; }
function diagnostic(d: Projection['diagnostic']): string { return d.status === 'diagnostic-not-promotable' ? 'Diagnostic evidence — not promotable' : d.status === 'not-configured' ? 'No diagnostic root configured' : `Diagnostic evidence unavailable: ${d.reason.replaceAll('-', ' ')}`; }
function CopyPath({ path }: { path: string }): React.JSX.Element { const [copied, setCopied] = useState(false); const copy = (): void => { const clipboard = navigator.clipboard; if (clipboard) void clipboard.writeText(path).then(() => setCopied(true)).catch(() => undefined); }; return <button type="button" className="figment__copy" title={path} aria-label={`Copy record path ${path}`} onClick={copy}>{copied ? 'Copied' : 'Copy path'}</button>; }
function Creators({ rows, truncated }: { rows: Projection['creators']; truncated: boolean }): React.JSX.Element { if (!rows.length) return <p className="figment__empty">No creator personas are recorded.</p>; return <><div className="figment__grid">{rows.map((c) => <article className="figment__card" key={c.id}><h2>{c.id}</h2><p><span className={`figment__badge figment__badge--${c.persona}`}>{c.persona === 'valid' ? 'Persona record' : 'Malformed persona record'}</span></p><dl><dt>LoRA tier</dt><dd>{c.loraTier ?? 'Not set'}</dd><dt>Trigger</dt><dd>{c.loraTrigger ?? 'Not set'}</dd><dt>Account tiers</dt><dd>{c.accountTiers.join(', ') || 'None recorded'}</dd></dl></article>)}</div>{truncated ? <p className="figment__notice">The creator list reached its safe display limit.</p> : null}</>; }
function Records({ rows, truncated }: { rows: RecordRow[]; truncated: boolean }): React.JSX.Element { if (!rows.length) return <p className="figment__empty">No driver, run, gate, or accepted-checkpoint records are available.</p>; return <><div className="figment__records">{rows.map((r) => <article className="figment__record" key={r.path}><div><h2>{r.type.replaceAll('-', ' ')}</h2><p>{r.creator ?? 'Shared Figment record'}{r.schema ? ` · ${r.schema}` : ''}</p></div><div className="figment__evidence"><span className={`figment__badge figment__badge--${r.reviewState}`}>{approval(r.reviewState)}</span>{r.machineGateState ? <span className={`figment__badge figment__badge--machine-${r.machineGateState}`}>Machine gate {r.machineGateState}</span> : null}<CopyPath path={r.path} /></div></article>)}</div>{truncated ? <p className="figment__notice">The record list reached its safe display limit.</p> : null}</>; }
function Research({ research }: { research: Projection['research'] }): React.JSX.Element { if (!research.available) return <p className="figment__empty">Research records are unavailable.</p>; if (!research.artifacts.length) return <p className="figment__empty">No research or book artifacts are recorded.</p>; return <><div className="figment__records">{research.artifacts.map((a) => <article className="figment__record" key={`${a.area}/${a.name}`}><div><h2>{a.name}</h2><p>{a.area === 'book' ? 'Book artifact' : 'Research artifact'} · {bytes(a.bytes)}</p></div><time dateTime={a.modifiedAt}>{new Date(a.modifiedAt).toLocaleDateString()}</time></article>)}</div>{research.truncated ? <p className="figment__notice">The artifact list reached its safe display limit.</p> : null}</>; }
export function FigmentWorkspace({ token, fetchImpl = fetch }: { token?: string; fetchImpl?: typeof fetch }): React.JSX.Element {
  const [projection, setProjection] = useState<Projection | null>(null); const [error, setError] = useState(false); const [refresh, setRefresh] = useState(0); const [tab, setTab] = useState<Tab>('creators');
  useEffect(() => { let live = true; setError(false); setProjection(null); void fetchImpl('/api/figment', { headers: token ? { authorization: `Bearer ${token}` } : undefined }).then(async (response) => { if (!response.ok) throw new Error('figment unavailable'); const decoded = valid(await response.json()); if (!decoded) throw new Error('invalid figment projection'); if (live) setProjection(decoded); }).catch(() => { if (live) setError(true); }); return () => { live = false; }; }, [fetchImpl, refresh, token]);
  if (!projection) return <main className="figment" aria-label="Figment workspace"><h1>Figment</h1><p role="status">{error ? 'Figment records are unavailable.' : 'Loading Figment records…'}</p>{error ? <button type="button" className="mc-btn" onClick={() => setRefresh((v) => v + 1)}>Retry</button> : null}</main>;
  if (!projection.available) return <main className="figment" aria-label="Figment workspace"><h1>Figment</h1><p className="figment__empty">The Figment project records are unavailable.</p></main>;
  return <main className="figment" aria-label="Figment workspace"><header className="figment__header"><div><h1>Figment</h1><p>Read-only project evidence. Machine-gate state does not approve a checkpoint.</p></div><p className={`figment__diagnostic figment__diagnostic--${projection.diagnostic.status}`}>{diagnostic(projection.diagnostic)}</p></header><div className="figment__tabs" role="tablist" aria-label="Figment workspace sections">{([['creators', 'Creators'], ['records', 'Runs & review'], ['research', 'Research']] as const).map(([id, label]) => <button key={id} type="button" role="tab" aria-selected={tab === id} className={tab === id ? 'figment__tab figment__tab--active' : 'figment__tab'} onClick={() => setTab(id)}>{label}</button>)}</div><section role="tabpanel" className="figment__panel">{tab === 'creators' ? <Creators rows={projection.creators} truncated={projection.creatorsTruncated} /> : tab === 'records' ? <Records rows={projection.records} truncated={projection.recordsTruncated} /> : <Research research={projection.research} />}</section></main>;
}
