/**
 * U8 — the read-only context-lifecycle routes over an injected fixture root (Fastify `inject`, the
 * `trace/routes.test.ts` idiom): the listing, the parsed sections, the path-safety rejections, and
 * the GET-only surface.
 *
 * The store fixtures below are written in the SAME rendering the hook library produces
 * (`scripts/hooks/lib/context_store.js:renderSections`) — the format contract itself is pinned on the
 * hook side by `tests/test_context_store.py`; these tests pin that this parser reads that format.
 */
import { afterEach, describe, expect, it } from 'vitest';
import { mkdtemp, mkdir, rm, writeFile, copyFile } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import Fastify from 'fastify';
import { parseSections, registerContextLifecycle, resolveStoreRoot } from './routes.ts';

/**
 * A store file produced by the REAL hook library, `scripts/hooks/lib/context_store.js:renderSections`
 * — not hand-written. It is what pins this route's parser (a deliberate second implementation, since
 * that library is CommonJS outside the dashboard's ESM graph) against the writer's actual output.
 *
 * REGENERATE from the repo root when the store format changes:
 *
 *   node -e "const s=require('./scripts/hooks/lib/context_store.js');require('fs').writeFileSync(
 *     'dashboard/server/contextLifecycle/__fixtures__/hook-written-store.ctx.md',
 *     s.renderSections([{heading:'Recent activity',body:'- Bash git status\n- Read scripts/hooks/lib/context_store.js'},
 *     {heading:'Resumed-session summary',body:'- user: pick the run back up\n- assistant: working [tool: Read]'},
 *     {heading:'Current gate',body:'awaiting the human review gate'},
 *     {heading:'Invariants',body:'Never spend real money.\nNever push to main.'},
 *     {heading:'North star',body:'Ship the Wave-1 platform slice.'}]),'utf8')"
 *
 * (The sections go in deliberately WRONG order — renderSections imposes the canonical one.)
 * `tests/test_context_store.py::test_committed_route_fixture_matches_the_writer` re-runs exactly that
 * from the Python side and fails if the committed bytes have drifted.
 */
const HOOK_WRITTEN_FIXTURE = fileURLToPath(
  new URL('./__fixtures__/hook-written-store.ctx.md', import.meta.url),
);

const PREAMBLE =
  '<!-- kb context-lifecycle store. Generated by the INERT context-lifecycle hooks; do not hand-edit. -->';

const STORE_TEXT = [
  PREAMBLE,
  '',
  '## North star',
  '',
  'Ship the Wave-1 platform slice.',
  '',
  '## Invariants',
  '',
  'Never spend real money.',
  'Never push to main.',
  '',
  '## Resumed-session summary',
  '',
  '- user: pick the run back up',
  '- assistant: working [tool: Read]',
  '',
  '## Recent activity',
  '',
  '- Bash git status',
  '',
].join('\n');

const tmpDirs: string[] = [];
afterEach(async () => {
  while (tmpDirs.length) {
    const dir = tmpDirs.pop()!;
    await rm(dir, { recursive: true, force: true });
  }
});

async function fixtureRoot(): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), 'ctxlife-routes-'));
  tmpDirs.push(root);
  await writeFile(join(root, 'session-alpha.ctx.md'), STORE_TEXT, 'utf8');
  await writeFile(join(root, 'session-beta.ctx.md'), `${PREAMBLE}\n\n## Current gate\n\nawaiting review\n`, 'utf8');
  // Neither of these is a store: a non-matching suffix and a directory.
  await writeFile(join(root, 'notes.md'), 'ignore me', 'utf8');
  await mkdir(join(root, 'nested.ctx.md'), { recursive: true });
  return root;
}

async function appFor(root: string) {
  const app = Fastify({ logger: false });
  registerContextLifecycle(app, root);
  await app.ready();
  return app;
}

describe('registerContextLifecycle', () => {
  it('GET /api/context-lifecycle lists only real store files', async () => {
    const app = await appFor(await fixtureRoot());
    const res = await app.inject({ method: 'GET', url: '/api/context-lifecycle' });
    expect(res.statusCode).toBe(200);
    const body = res.json() as { available: boolean; sessions: Array<{ sessionId: string; modifiedAt: string }> };
    expect(body.available).toBe(true);
    expect(body.sessions.map((s) => s.sessionId).sort()).toEqual(['session-alpha', 'session-beta']);
    expect(Number.isNaN(Date.parse(body.sessions[0].modifiedAt))).toBe(false);
    await app.close();
  });

  it('reports a missing store root as unavailable rather than an error — the inert-hooks state', async () => {
    const app = await appFor(join(await fixtureRoot(), 'does-not-exist'));
    const res = await app.inject({ method: 'GET', url: '/api/context-lifecycle' });
    expect(res.statusCode).toBe(200);
    expect(res.json()).toMatchObject({ available: false, sessions: [] });
    await app.close();
  });

  it('GET /api/context-lifecycle/:sessionId returns the sections in file order', async () => {
    const app = await appFor(await fixtureRoot());
    const res = await app.inject({ method: 'GET', url: '/api/context-lifecycle/session-alpha' });
    expect(res.statusCode).toBe(200);
    const body = res.json() as { sessionId: string; sections: Array<{ heading: string; body: string }> };
    expect(body.sessionId).toBe('session-alpha');
    expect(body.sections.map((s) => s.heading)).toEqual([
      'North star',
      'Invariants',
      'Resumed-session summary',
      'Recent activity',
    ]);
    expect(body.sections[0].body).toBe('Ship the Wave-1 platform slice.');
    expect(body.sections[1].body).toBe('Never spend real money.\nNever push to main.');
    await app.close();
  });

  it('404s for a session with no store', async () => {
    const app = await appFor(await fixtureRoot());
    const res = await app.inject({ method: 'GET', url: '/api/context-lifecycle/session-gamma' });
    expect(res.statusCode).toBe(404);
    expect(res.json()).toEqual({ error: 'no-store' });
    await app.close();
  });

  it('rejects every id that is not a safe file stem, before touching the filesystem', async () => {
    const app = await appFor(await fixtureRoot());
    for (const id of ['..', '.hidden', '%2e%2e', 'a%2Fb', 'a:b', 'a b', 'x'.repeat(129)]) {
      const res = await app.inject({ method: 'GET', url: `/api/context-lifecycle/${id}` });
      // 414 = Fastify rejected an over-long URI before routing; still a rejection, still unread.
      expect([400, 404, 414], id).toContain(res.statusCode);
      if (res.statusCode === 400) expect(res.json()).toEqual({ error: 'invalid-session-id' });
    }
    await app.close();
  });

  it('exposes GET only — no write verb is routed', async () => {
    const app = await appFor(await fixtureRoot());
    for (const method of ['POST', 'PUT', 'PATCH', 'DELETE'] as const) {
      const list = await app.inject({ method, url: '/api/context-lifecycle' });
      expect(list.statusCode).toBe(404);
      const one = await app.inject({ method, url: '/api/context-lifecycle/session-alpha' });
      expect(one.statusCode).toBe(404);
    }
    await app.close();
  });
});

describe('cross-parser pin: this route reads what the hook library writes', () => {
  it('parses a store file generated by scripts/hooks/lib/context_store.js:renderSections', async () => {
    const root = await mkdtemp(join(tmpdir(), 'ctxlife-hookfixture-'));
    tmpDirs.push(root);
    await copyFile(HOOK_WRITTEN_FIXTURE, join(root, 'hook-written.ctx.md'));

    const app = await appFor(root);
    const res = await app.inject({ method: 'GET', url: '/api/context-lifecycle/hook-written' });
    expect(res.statusCode).toBe(200);
    const body = res.json() as { sections: Array<{ heading: string; body: string }> };

    // The writer's FIXED order, read back through this parser — including the two U7 seam headings
    // spelled byte-identically to what regrounding_hook.js extracts.
    expect(body.sections.map((s) => s.heading)).toEqual([
      'North star',
      'Invariants',
      'Current gate',
      'Resumed-session summary',
      'Recent activity',
    ]);
    expect(body.sections[0].body).toBe('Ship the Wave-1 platform slice.');
    expect(body.sections[1].body).toBe('Never spend real money.\nNever push to main.');
    expect(body.sections[4].body).toContain('- Bash git status');
    // The generated preamble is not a section and must not leak into one.
    expect(body.sections.some((s) => s.body.includes('do not hand-edit'))).toBe(false);
    await app.close();
  });

  it('the committed fixture really is writer output, not a hand-written lookalike', () => {
    const text = readFileSync(HOOK_WRITTEN_FIXTURE, 'utf8');
    expect(text.startsWith(PREAMBLE)).toBe(true);
    // renderSections' exact block shape: heading, blank line, body, blank line.
    expect(text).toContain('## North star\n\nShip the Wave-1 platform slice.\n');
  });
});

describe('parseSections', () => {
  it('drops the preamble and keeps heading order', () => {
    expect(parseSections(STORE_TEXT).map((s) => s.heading)).toEqual([
      'North star',
      'Invariants',
      'Resumed-session summary',
      'Recent activity',
    ]);
  });

  it('returns nothing for text with no headings', () => {
    expect(parseSections('just a preamble\nand a line')).toEqual([]);
  });
});

describe('resolveStoreRoot', () => {
  it('prefers KB_CONTEXT_STORE_DIR and otherwise stays outside the repo', () => {
    expect(resolveStoreRoot({ KB_CONTEXT_STORE_DIR: 'C:/fixture/store' } as NodeJS.ProcessEnv)).toBe(
      'C:/fixture/store',
    );
    const fallback = resolveStoreRoot({ LOCALAPPDATA: 'C:/Users/x/AppData/Local' } as NodeJS.ProcessEnv);
    expect(fallback).toBe(join('C:/Users/x/AppData/Local', 'kb-context-lifecycle'));
  });
});
